-- Run this in Supabase SQL Editor (project: xvnloxyipwkvvamumtbc)
-- Creates visit log table used by src/db.py (SUPABASE_LOG_TABLE=log_user).

create table if not exists public.log_user (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  exit_time timestamptz null,
  session_id text not null,
  ip_address text null
);

alter table public.log_user enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update on table public.log_user to anon, authenticated;
grant usage, select on sequence public.log_user_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'log_user'
      and policyname = 'log_user_insert_anon'
  ) then
    create policy log_user_insert_anon
      on public.log_user
      for insert
      to anon, authenticated
      with check (true);
  end if;
end$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'log_user'
      and policyname = 'log_user_select_anon'
  ) then
    create policy log_user_select_anon
      on public.log_user
      for select
      to anon, authenticated
      using (true);
  end if;
end$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'log_user'
      and policyname = 'log_user_update_anon'
  ) then
    create policy log_user_update_anon
      on public.log_user
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end$$;
